---
kind: template
load: docker-build-multiarch.yaml
data:
  dockerfiledir: .
  hubimagename: fh6-telemetry-dashboard
  repotype: hub
  imagetag: latest
  branches: ['master', 'main']
  buildarch: linux/arm64/v8,linux/amd64
